objects/TestClassAutomation__c/TestClassAutomation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The data of this custom setting is used for test classes automation</description>
    <label>TestClassAutomation</label>
</CustomObject>

objects/TestClassAutomation__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/TestClassAutomation__c/fields/Recipients__c.field-meta.xml
<CustomField>
    <fullName>Recipients__c</fullName>
    <description>CSV of email ids</description>
    <label>Recipients</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/TestClassAutomation__c/fields/Test_Classes__c.field-meta.xml
<CustomField>
    <fullName>Test_Classes__c</fullName>
    <description>CSV of test classes names</description>
    <label>Test Classes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/RunTestClassesScheduler.cls
global class RunTestClassesScheduler implements Schedulable{
	public static String baseUrl = URL.getSalesforceBaseUrl().toExternalForm()+'/services/data/v49.0/tooling/';
	global void execute(SchedulableContext ctx){
		String toolingAPIMethodName = 'runTestsAsynchronous';
		String body;
		for (TestClassAutomation__c customSettingRecord : TestClassAutomation__c.getAll().values()){
			List<String> testClassesNames = new List<String>();
			if (customSettingRecord.Test_Classes__c != null){
				testClassesNames.addAll(customSettingRecord.Test_Classes__c.split(','));
			}
			List<String> recipientsList;
			if (String.isNotBlank(customSettingRecord.Recipients__c)){
				recipientsList = customSettingRecord.Recipients__c.split(',');
			} else{
				recipientsList = new List<String>{UserInfo.getUserEmail()};
			}
			body = UtilityMethods.createBody(testClassesNames);
			UtilityMethods.createRequest(baseUrl, toolingAPIMethodName, body, customSettingRecord.Mode__c, recipientsList);
		}
	}
}